title: Fuzzing with Fandango
author: José Antonio Zamudio Amaya, Marius Smytzek, and Andreas Zeller
logo: fandango.png
copyright: 2024 CISPA Helmholtz Center for Information Security (www.cispa.de). All Rights Reserved.
exclude_patterns: [BookIntro.md]

bibtex_bibfiles:
  - fandango.bib

latex:
  latex_documents:
     targetname: fandango.tex

execute:
  execute_notebooks: cache
  stderr_output: warn
  timeout: 300

parse:
  myst_enable_extensions:
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

html:
  announcement: '<p>💃 Fandango is currently in development - see our <a href="https://github.com/fandango-fuzzer/fandango/issues"  style="color:white;">list of bugs and incomplete features</a>. Expect a first stable release in April 2025.</p>'
  use_issues_button: true
  use_repository_button: true