name: Check code formatting

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch: # Enables manual execution from the Actions tab

jobs:
  black-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.11 ]  # Python version to run

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install black mypy

      - name: Check formatting with black
        run: |
          black --check src
      
      - name: Get changed Python files
        id: changed-python-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            src/**/*.py

      - name: Check typing with mypy
        run: |
          echo "Checking files: ${{ steps.changed-python-files.outputs.all_changed_files }}"
          for file in ${{ steps.changed-python-files.outputs.all_changed_files }}; do
            mypy --check-untyped-defs "$file"
          done