name: Build and upload to PyPI

on:
  release:
    types: [published]  # Trigger the workflow when a release is published
  pull_request:
    branches: [main] # Trigger the workflow when a pull request on main is opened, publishing is disabled for PRs
  workflow_dispatch: # Enables manual execution from the Actions tab

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false  # Ensures all builds run even if some fail
      matrix:
        include:
          - os: linux-intel
            runs-on: ubuntu-latest
          - os: linux-arm
            runs-on: ubuntu-24.04-arm
          - os: macos-arm
            runs-on: macos-latest
            # currently not working, see https://github.com/amykyta3/speedy-antlr-tool/issues/18
            # - os: windows
            #   runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.2
        env:
          FANDANGO_REQUIRE_BINARY_BUILD: "1" # Force binary build

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/fandango-fuzzer
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}  # Use the secret PyPI token
      