name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - docs/**
  workflow_dispatch: # Enables manual execution from the Actions tab

permissions:
  pages: write
  id-token: write

jobs:
  deploy-book:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install "sphinx==6.2.1" "docutils<0.21"
        pip install fandango-fuzzer jupyter-book pyppeteer ghp-import black

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build docs

    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "docs/_build/html"

    # Deploy the book's HTML to GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
