name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - docs/**
  workflow_dispatch: # Allows manual triggering from the Actions tab

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the source repository
    - name: Checkout the source repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install -e .
        pip install jupyter-book pyppeteer ghp-import black

    # Step 4: Locate Fandango and add to PATH
    - name: Locate Fandango and add to PATH
      run: |
        which fandango
        echo "/opt/hostedtoolcache/Python/3.13.1/x64/bin/fandango" >> $GITHUB_PATH
        fandango --help

    # Step 5: Build the documentation
    - name: Build the book
      run: |
        jupyter-book build docs

    # Step 6: Clone the target repository
    - name: Clone the target repository
      run: |
        git clone https://github.com/fandango-fuzzer/fandango-fuzzer.github.io.git target-repo
        cd target-repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 7: Copy the built HTML files to the target repository
    - name: Copy built files to the target repository
      run: |
        cp -r docs/_build/html/* target-repo/

    # Step 8: Commit and push changes to the target repository
    - name: Deploy to GitHub Pages
      run: |
        cd target-repo
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update GitHub Pages site" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
