name: GitHub Pages Deployment

on:
  push:
    branches:
      - main
    paths:
      - docs/**
  workflow_dispatch: # Enables manual execution from the Actions tab

permissions:
  contents: write # Needed for pushing to the other repository
  id-token: write

jobs:
  deploy-book:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        pip install -e .
        pip install jupyter-book pyppeteer ghp-import black

    - name: Locate Fandango and add to PATH
      run: |
        which fandango 
        echo "/opt/hostedtoolcache/Python/3.13.1/x64/bin/fandango" >> $GITHUB_PATH
        fandango --help

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build docs

    # Push built HTML to fandango-fuzzer.github.io repository
    - name: Deploy to fandango-fuzzer.github.io
      env:
        TARGET_REPO: fandango-fuzzer/fandango-fuzzer.github.io
        TARGET_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Clone the target repository
        git clone --depth 1 https://github.com/${{ env.TARGET_REPO }} target-repo
        cd target-repo
        
        # Remove all existing files
        git rm -rf . || true

        # Copy new HTML files
        cp -r ../docs/_build/html/* .

        # Commit and push changes
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update GitHub Pages site"
        git push origin ${{ env.TARGET_BRANCH }}
