# GitHub Actions Workflow: Static type checking with mypy

name: Type checking

on:
  push:
    branches:
      - dev   # Run type checking on pushes to the dev branch
  pull_request:
    branches:
      - main  # Run type checking on pull requests targeting the main branch
      - dev   # Run type checking on pull requests targeting the dev branch
  workflow_dispatch: # Enables manual execution from the Actions tab

jobs:
  mypy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner provided by GitHub

    strategy:
      matrix:
        python-version: [ 3.11 ]  # Python version to run

    steps:
      # Step 1: Checkout the repository's code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Get changed files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            src/**/*.py
            src/**.py
            tests/**/*.py
            tests/**.py

      # Step 3: Set up Python environment
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      # Step 4: Install mypy
      - name: Install mypy
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          pip install -e .

      # Step 6: Run mypy on changed files
      - name: Run mypy on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          COMMAND="echo \"${{ steps.changed-files.outputs.all_changed_files }}\" | tr ' ' '\n' | xargs -I {} mypy \"{}\""
          echo $COMMAND
          eval $COMMAND

