# GitHub Actions Workflow: Python Tests
# This workflow automates the process of running tests on Python code using pytest.
# It triggers on pushes to the main and dev branches, and on pull requests targeting main.

name: Python Tests  # Workflow name, visible in the Actions tab

on:
  push:
    branches:
      - main  # Run tests on pushes to the main branch
      - dev   # Run tests on pushes to the dev branch
  pull_request:
    branches:
      - main  # Run tests on pull requests targeting the main branch

jobs:
  test:
    # Define the environment this job will run on
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner provided by GitHub

    strategy:
      # Matrix lets you run the job for multiple Python versions (in this case, only Python 3.11)
      matrix:
        python-version: [ 3.11 ]

    steps:
      # Step 1: Checkout the repository's code
      - name: Checkout code
        uses: actions/checkout@v3  # Official GitHub action to checkout the repository's code

      # Step 2: Set up the Python environment
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4  # Official action to set up the specified Python version
        with:
          python-version: ${{ matrix.python-version }}  # Python version from matrix strategy

      # Step 3: Install system-level dependencies required by the project
      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y python3-dev graphviz libgraphviz-dev pkg-config  # Install essential system packages
          pip install pygraphviz  # Install pygraphviz via pip

      # Step 4: Install Python dependencies (FANDANGO and additional libraries)
      - name: Install FANDANGO dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -e .  # Install the project in editable mode
          pip install -r requirements.txt  # Install all dependencies listed in requirements.txt

      # Step 5: Run the test suite using pytest
      - name: Run tests
        run: |
          pytest  # Execute tests with pytest
